### ISSUE TITLE
Rooms route not working

### ISSUE THREAD

**Issue by bdougie** [imdoingotherthings/bloc-chat-ember#2]
I am not sure the reasoning for why we are creating room routes can you explain? Because the branch we are on was username, which doesn't have to do with rooms. I'm confused.

**Comment by imdoingotherthings** [comment]
Yes. I called the branch `username` because the ultimate goal of the checkpoint is to store the username of the user when they create one. 
The room routing is to select the given room. That way when a user enters the room they are able to create a username. Which then enables the user to chat inside any room. 

Are we solely trying to achieve creating a username and storing it for the user on this checkpoint?

**Comment by bdougie** [comment]
yes, this checkpoint is just creating a username and it shouldn't be at the room level. Think slack, you do not need to enter your name everytime you change rooms. You just enter your name once. The username modal should be on the application.hbs and checking a ember-cookies if it exists, that is it.

Create a new branch doing that, I still work on the routing, but that is a separate issue

**Comment by bdougie** [comment]
Need to add room_id to the model here 👉🏾 https://github.com/imdoingotherthings/bloc-chat-ember/blob/username/app/models/room.js#L4

That is why it was null

**Comment by bdougie** [comment]
Also this is an issue: you have a space in your route https://github.com/imdoingotherthings/bloc-chat-ember/blob/username/app/router.js#L12

Both this and the issue above is the reason why this was not working. I can't stress enough, please please please check for typos
